#pragma once
enum STATE { IDLE, MOVING, HURT, DEAD, USING };
enum LOOKING { DOWN, RIGHT, UP, LEFT, NO };
enum CHARACTERS { ISAAC, MAGDALENE, CAIN, SAMSON };
enum DIAGONALS { NONE, NE, SE, SW, NW };
enum BULLET_DIRECTION { N, N_E, E, S_E, S, S_W, W, N_W };
enum HEARTS { HALF_RED, FULL_RED, HALF_SOUL, FULL_SOUL, HALF_BLACK, FULL_BLACK, HALF_ETERNAL };